# Generated by Django 3.1.7 on 2021-04-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonuses',
            field=models.IntegerField(null=True, verbose_name='Баллы'),
        ),
    ]
