# Generated by Django 3.1.7 on 2021-04-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_bonuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bonuses',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
    ]
