# Generated by Django 3.1.7 on 2021-03-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('menu', '0004_auto_20210316_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='ФИО')),
                ('address', models.CharField(max_length=55, verbose_name='Адрес доставки')),
                ('phone', models.IntegerField(verbose_name='Номер')),
                ('product', models.ManyToManyField(to='menu.Menu', verbose_name='Товар')),
                ('user', models.ManyToManyField(to='account.Profile', verbose_name='Пользователь')),
            ],
        ),
    ]
