# Generated by Django 3.1.7 on 2021-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('cancellation ', 'Отменен'), ('implemented ', 'Реализован'), ('in work', 'В работе')], max_length=40, null=True, verbose_name='Статус заказа'),
        ),
    ]
