# Generated by Django 3.1.7 on 2021-03-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210328_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('1', 'Отменен'), ('2', 'Реализован'), ('3', 'В работе')], default='3', max_length=40, verbose_name='Статус заказа'),
        ),
    ]
