# Generated by Django 3.1.7 on 2021-03-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210313_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridients',
            options={'verbose_name': 'Состав', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RenameField(
            model_name='ingridients',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
